version: "3.8"
services:
    backend:
        build:
            context: ./docker/node
        restart: "unless-stopped"
        ports:
            - 8080:8080
        volumes:
            - ./backend:/code
        networks:
            - weather-forecast-internal

    frontend:
        build:
            context: ./docker/node
        restart: "unless-stopped"
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/code
        networks:
            - weather-forecast-internal

networks:
    weather-forecast-internal:
